# Generated by Django 4.2.5 on 2024-01-02 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_categories_alter_course_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
